# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('post', models.CharField(max_length=6000)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
