# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blblogger', '0002_auto_20161116_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(editable=False),
        ),
    ]
