# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 20:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blblogger', '0003_auto_20161116_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 16, 20, 30, 17, 572866, tzinfo=utc)),
        ),
    ]
